# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f19e8897e59dcf2b84df02c5ca1dd6e162607695e621f18506c7ad5df7e3ebdf0ec10c82a8d5cba66adaeb5983ddb3c38eb05216dfca343652a6bb5ddea0df0c

test:
  secret_key_base: d9c4d3afb185a1bd3efc0f3abb06c1a0317aa2b9cd2e94a35189ce0052d875f7c4ddd9a37903d542ba90dbdd17c6608443d4071f33c496769128c0d4d2478a49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
